silver_config = {

 "orders": {
    "primary_key": ["order_id"],
    "not_null": ["order_id","customer_id"],
    "dedup_columns": ["order_id"]
 },

 "order_items": {
    "primary_key": ["order_id","order_item_id"],
    "not_null": ["order_id","product_id"],
    "dedup_columns": ["order_id","order_item_id"]
 },

 "order_payments": {
    "primary_key": ["order_id","payment_sequential"],
    "not_null": ["order_id"],
    "dedup_columns": ["order_id","payment_sequential"]
 },

 "order_reviews": {
    "primary_key": ["review_id"],
    "not_null": ["review_id"],
    "dedup_columns": ["review_id"]
 }
}
